"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from .env file using python-decouple
# Default is ONLY for Docker build (collectstatic). Always set in production!
SECRET_KEY = config('SECRET_KEY', default='build-time-secret-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
# cast=bool converts string 'True'/'False' to Python boolean
DEBUG = config('DEBUG', default=True, cast=bool)

# Csv class splits comma-separated values into a list
# Default includes localhost for development
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# Railway deployment: Auto-add Railway's domain and healthcheck domain
# Railway automatically sets RAILWAY_PUBLIC_DOMAIN and PORT environment variables
import os
RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN')
if RAILWAY_PUBLIC_DOMAIN:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# Railway healthcheck uses healthcheck.railway.app
# Detect Railway by checking for PORT or RAILWAY_ENVIRONMENT variables
if os.environ.get('PORT') or os.environ.get('RAILWAY_ENVIRONMENT'):
    ALLOWED_HOSTS.append('healthcheck.railway.app')


# =============================================================================
# SECURITY SETTINGS (Day 25)
# =============================================================================

# 1. XSS Filter - Tells browser to block suspected XSS (Cross-Site Scripting) attacks
#    Example: Blocks malicious scripts like <script>alert('hack')</script>
SECURE_BROWSER_XSS_FILTER = True

# 2. Content Type Sniffing Protection - Prevents browsers from guessing file types
#    Example: Stops a .txt file from being executed as JavaScript
SECURE_CONTENT_TYPE_NOSNIFF = True

# 3. Clickjacking Protection - Prevents your site from being embedded in iframes
#    Options: 'DENY' (no iframes), 'SAMEORIGIN' (only your domain can iframe)
#    Example: Stops attackers from loading your site inside their malicious page
X_FRAME_OPTIONS = 'DENY'

# 4. HSTS (HTTP Strict Transport Security) - Forces browsers to use HTTPS
#    Value is in seconds.
#    Development: 3600 (1 hour) - short for testing
#    Production: 31536000 (1 year) - long for security
#    Example: Auto-converts http://yoursite.com to https://yoursite.com
SECURE_HSTS_SECONDS = 3600 if DEBUG else 31536000

# 5. HSTS for Subdomains - Applies HTTPS to all subdomains too
#    Example: Both site.com and api.site.com will use HTTPS
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# 6. HSTS Preload - Allows your site to be added to browser's preload list
#    This makes browsers ALWAYS use HTTPS for your domain (even first visit)
SECURE_HSTS_PRELOAD = True

# 7. SSL/HTTPS Redirect - Automatically redirects HTTP to HTTPS
#    Development: False (localhost doesn't have SSL)
#    Production: True (auto-redirect HTTP → HTTPS)
SECURE_SSL_REDIRECT = not DEBUG  # False in dev, True in production

# 8. Secure Cookies - Ensures cookies are only sent over HTTPS
#    Development: False (we don't have HTTPS locally)
#    Production: True (cookies only sent over HTTPS)
SESSION_COOKIE_SECURE = not DEBUG  # False in dev, True in production
CSRF_COOKIE_SECURE = not DEBUG  # False in dev, True in production

# 9. HttpOnly Cookies - Prevents JavaScript from reading cookies
#    This protects against XSS attacks trying to steal session cookies
#    Example: Even if attacker injects <script>, they can't read your session
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# 10. SameSite Cookie Protection - Cookies only sent from your own site
#    Options: 'Strict' (most secure), 'Lax' (balanced), 'None' (least secure)
#    'Lax' = Cookie sent with navigation but not with cross-site POST requests
#    This prevents CSRF attacks from other websites
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# 11. Session Cookie Age - How long sessions last (in seconds)
#    Default: 1209600 seconds = 2 weeks
#    Example: User stays logged in for 2 weeks, then must re-login
SESSION_COOKIE_AGE = 1209600  # 2 weeks

# 12. Session Expire on Browser Close - Session ends when browser closes
#    False = Session persists even after closing browser (for convenience)
#    True = More secure, but users must login every time they open browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# =============================================================================
# CORS CONFIGURATION (Topic 23)
# =============================================================================
# CORS = Cross-Origin Resource Sharing
# Allows your frontend (React/Vue) running on different origin to access API

# Development: Allow specific origins (most secure approach)
# Read from .env file and split by comma into a list
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:5173',
    cast=Csv()
)

# Alternative for development only: Allow all origins (NOT for production!)
# CORS_ALLOW_ALL_ORIGINS = True  # ⚠️ NEVER use this in production!

# Allow credentials (cookies, auth headers) to be sent
# Required if your frontend needs to send auth tokens or cookies
CORS_ALLOW_CREDENTIALS = True

# Which HTTP methods are allowed from other origins
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',  # Required for preflight requests
    'PATCH',
    'POST',
    'PUT',
]

# Which headers can be sent in requests from other origins
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',      # For token auth (Bearer token)
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',       # For CSRF protection
    'x-requested-with',
]

# Django Debug Toolbar Configuration
INTERNAL_IPS = [
    '127.0.0.1',  # Allow debug toolbar on localhost
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'products', 
    'rest_framework',
    'rest_framework.authtoken',
    'authentication',
    'django_filters',  # For advanced filtering
    'debug_toolbar',   # Django Debug Toolbar for query debugging
    'drf_spectacular', # API Documentation (Topic 22)
    'corsheaders',     # CORS Configuration (Topic 23)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # Debug Toolbar (should be early)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS (MUST be before CommonMiddleware)
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Flexible database configuration:
# - Development: Uses SQLite by default (simple, no setup needed)
# - Production: Uses PostgreSQL (set DB_ENGINE in .env or DATABASE_URL for Railway)

# Railway provides DATABASE_URL, parse it if available
from urllib.parse import urlparse

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Parse DATABASE_URL (Railway format: postgresql://user:password@host:port/dbname)
    # Handle both postgres:// and postgresql:// schemes
    if DATABASE_URL.startswith('postgres://'):
        DATABASE_URL = DATABASE_URL.replace('postgres://', 'postgresql://', 1)
    parsed = urlparse(DATABASE_URL)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path[1:],  # Remove leading '/'
            'USER': parsed.username,
            'PASSWORD': parsed.password,
            'HOST': parsed.hostname,
            'PORT': parsed.port or '5432',
        }
    }
else:
    # Fall back to individual DB_* variables or SQLite
    DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')
    
    if DB_ENGINE == 'django.db.backends.postgresql':
        # PostgreSQL configuration (production)
        DATABASES = {
            'default': {
                'ENGINE': DB_ENGINE,
                'NAME': config('DB_NAME', default='myshop_db'),
                'USER': config('DB_USER', default='myshop_user'),
                'PASSWORD': config('DB_PASSWORD', default=''),
                'HOST': config('DB_HOST', default='localhost'),
                'PORT': config('DB_PORT', default='5432'),
            }
        }
    else:
        # SQLite configuration (development)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL prefix for static files (e.g., /static/css/style.css)
STATIC_URL = 'static/'

# Directory where collectstatic will collect all static files
# In production, run: python manage.py collectstatic
# This copies all static files from your apps into this single folder
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration for serving static files in production
# This enables compression and caching for better performance
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Additional locations of static files (optional)
# Use this if you have project-level static files outside of apps
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

# Media files (User uploaded files like product images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Pagination
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS' : 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE' : 3  ,           #sets the default number of items per page

    'DEFAULT_AUTHENTICATION_CLASSES' : [
        'rest_framework.authentication.TokenAuthentication',     #simple token
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',  # Will add JWT later
    ],
    
    # API Documentation (Topic 22)
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # =============================================================================
    # GLOBAL PERMISSION STRATEGY (Topic 21 - Day 26)
    # =============================================================================
    # This sets the DEFAULT permission for ALL API endpoints
    # Benefits:
    # 1. No need to add @permission_classes to every view
    # 2. Secure by default (better than accidentally leaving endpoints open)
    # 3. Cleaner code (less repetition)
    # 
    # How it works:
    # - If you DON'T override in a view → uses this default
    # - If you DO override in a view → view's permission takes priority
    #
    # Common strategies:
    # Option 1: 'rest_framework.permissions.IsAuthenticated' → ALL endpoints require login
    # Option 2: 'rest_framework.permissions.IsAuthenticatedOrReadOnly' → Read=public, Write=auth
    # Option 3: 'rest_framework.permissions.AllowAny' → Everything public (not recommended)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  # GET=public, POST/PUT/DELETE=auth
    ],
    
    # Throttling (Rate Limiting)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',   # For anonymous users
        'rest_framework.throttling.UserRateThrottle',   # For authenticated users
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute',   # Anonymous: 5 requests per minute
        'user': '100/minute', # Authenticated: 100 requests per minute
        'burst': '3/minute',  # For expensive operations (custom scope)
        'strict_anon': '2/minute',  # Extra strict for sensitive endpoints
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME' : timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,

}

# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',  # Unique identifier for this cache
    }
}

# Logging Configuration for Debugging
# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
# Development: More verbose, debug level logging
# Production: Less noise, errors to separate file

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    # Formatters define how log messages look
    'formatters': {
        'verbose': {
            # Full details: level, time, module, process, thread, message
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            # Just level and message (for console in production)
            'format': '{levelname} {message}',
            'style': '{',
        },
        'production': {
            # Production format: includes timestamp and request info
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    
    # Handlers define WHERE logs go
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose' if DEBUG else 'production',
        },
        'file': {
            # General log file (all logs)
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'debug.log' if DEBUG else BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose' if DEBUG else 'production',
        },
        'error_file': {
            # Separate file for errors only (production)
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'formatter': 'production',
            'level': 'ERROR',  # Only ERROR and CRITICAL
        },
    },
    
    # Root logger (catches everything not handled by specific loggers)
    'root': {
        'handlers': ['console', 'file'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },
    
    # Specific loggers for different parts of the app
    'loggers': {
        'products': {
            # Your app's logger
            'handlers': ['console', 'file'] if DEBUG else ['console', 'file', 'error_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'django': {
            # Django framework logs
            'handlers': ['console', 'file'] if DEBUG else ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            # HTTP request errors (4xx, 5xx) - important for production
            'handlers': ['console', 'file', 'error_file'],
            'level': 'WARNING' if DEBUG else 'ERROR',
            'propagate': False,
        },
        'django.security': {
            # Security-related logs (suspicious activity)
            'handlers': ['console', 'file', 'error_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# =============================================================================
# API DOCUMENTATION SETTINGS (Topic 22)
# =============================================================================
SPECTACULAR_SETTINGS = {
    'TITLE': 'MyShop API',
    'DESCRIPTION': 'Professional E-commerce API with DRF',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False, # False means don't include raw schema in UI 
    # Optional: Add metadata
    'CONTACT': {
        'name': 'Prachi Khandelwal',
        'email': 'your-email@example.com',
    },
}

# =============================================================================
# ERROR REPORTING - SENTRY (Topic 25)
# =============================================================================
# Sentry provides real-time error tracking and monitoring for production
# 
# Setup Steps:
# 1. Create free account at https://sentry.io
# 2. Create a new Django project
# 3. Copy your DSN (looks like: https://xxx@xxx.ingest.sentry.io/xxx)
# 4. Add SENTRY_DSN to your .env file
# 5. Run: poetry add sentry-sdk

# Get Sentry DSN from environment (empty = disabled)
SENTRY_DSN = config('SENTRY_DSN', default='')

# Only initialize Sentry in production (when DEBUG=False and DSN is set)
if not DEBUG and SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        
        # Performance monitoring (optional)
        # Captures 10% of transactions for performance monitoring
        traces_sample_rate=0.1,
        
        # Send user info with errors (helps debugging)
        send_default_pii=True,
        
        # Environment tag (helps filter errors by environment)
        environment=config('ENVIRONMENT', default='production'),
    )