# Generated by Django 5.2.5 on 2025-11-27 14:22

import products.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_options_product_product_price_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(validators=[products.validators.validate_no_scripts]),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, validators=[products.validators.validate_no_scripts]),
        ),
    ]
